### ISSUE TITLE
Doesn't compile with 7.9

### ISSUE THREAD

**Issue by Fuuzetsu** [ndmitchell/derive#1]
There were some changes in Template Haskell API.

I made a pull request with a fix to the same problem to aeson already, you can have a look at it [here](https://github.com/bos/aeson/pull/189). I'm using GHC-7.9.20140308

```
Configuring derive-2.5.13...
Building derive-2.5.13...
Preprocessing library derive-2.5.13...
[ 1 of 65] Compiling Language.Haskell.TH.Compat ( Language/Haskell/TH/Compat.hs, dist/dist-sandbox-c4fc5f8b/build/Language/Haskell/TH/Compat.o )

Language/Haskell/TH/Compat.hs:31:23:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH),
      ‘ClassI’ (imported from Language.Haskell.TH),
      ‘Clause’ (imported from Language.Haskell.TH)

Language/Haskell/TH/Compat.hs:32:25:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH),
      ‘ClassI’ (imported from Language.Haskell.TH),
      ‘Clause’ (imported from Language.Haskell.TH)

Language/Haskell/TH/Compat.hs:33:11:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH),
      ‘ClassI’ (imported from Language.Haskell.TH),
      ‘Clause’ (imported from Language.Haskell.TH)
Failed to install derive-2.5.13
```
