### ISSUE TITLE
support haskell-src-exts-1.21+?

### ISSUE THREAD

**Issue by juhp** [ndmitchell/derive#36]
This is not urgent at all, but just a heads-up that since derive-2.6.5 does not build with haskell-src-exts-1.21 (lts-14), the package will probably get dropped from Fedora 32 or later.
```
src/Language/Haskell.hs:286:29: error:
    Not in scope: data constructor ‘KindStar’
    |
286 |           f (KindedVar _ x (KindStar _)) = Just $ prettyPrint x
    |                             ^^^^^^^^
```
Anyway it might be good to add it to Stackage if you plan to continue maintaining it actively, otherwise it is fine I guess. :)

**Comment by ndmitchell** [comment]
I consider Derive to be unmaintained. If no one else steps up, it's dead - I explicitly removed it from Stackage and I'd recommend removing it from Fedora too.

**Comment by juhp** [comment]
Okay, sure, thanks
